/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseInforHomeView: typeof import('./src/components/StudentComponents/StudentPersonal/BaseInfor/BaseInforHomeView.vue')['default']
    ClassMaterialsHomeView: typeof import('./src/components/StudentComponents/StudentClass/SelfStudy/ClassMaterialsHomeView.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    LearnCenterHomeView: typeof import('./src/components/StudentComponents/StudentClass/LearnCenter/LearnCenterHomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfStudy: typeof import('./src/components/StudentComponents/StudentClass/SelfStudy/SelfStudy.vue')['default']
    SemesterScheduleHomeView: typeof import('./src/components/StudentComponents/StudentPersonal/SemesterSchedule/SemesterScheduleHomeView.vue')['default']
    StudentHomeRightCenter: typeof import('./src/components/StudentComponents/StudentHome/StudentHomeRightCenter.vue')['default']
    StudentHomeRightDown: typeof import('./src/components/StudentComponents/StudentHome/StudentHomeRightDown.vue')['default']
    StudentHomeRightTop: typeof import('./src/components/StudentComponents/StudentHome/StudentHomeRightTop.vue')['default']
    StudentHomeView: typeof import('./src/components/StudentComponents/StudentHome/StudentHomeView.vue')['default']
    StudentLeftList: typeof import('./src/components/StudentComponents/StudentLeftList.vue')['default']
    StudentMain: typeof import('./src/components/StudentComponents/StudentMain.vue')['default']
    StudentTop: typeof import('./src/components/StudentComponents/StudentTop.vue')['default']
    StudyInfo: typeof import('./src/components/StudentComponents/StudentClass/StudyInfo/StudyInfo.vue')['default']
    TraningPlan: typeof import('./src/components/StudentComponents/StudentPersonal/TraningPlan/TraningPlan.vue')['default']
    VoiceTranslate: typeof import('./src/components/VoiceTranslate.vue')['default']
  }
}
